Repository Nikhil-2002/development_Hactoberfest23, pull requests merged in 2023-10, with the labels that each got.

#14 added html page in Landing_page
  Landing_page/css/styles.css
  Landing_page/images/TechCrunch.png
  Landing_page/images/bizinsider.png
  Landing_page/images/dog-img.jpg
  Landing_page/images/iphone6.png
  Landing_page/images/lady-img.jpg
  Landing_page/images/mashable.png
  Landing_page/images/tnw.png
  Landing_page/index.html
Labels: hacktoberfest-accepted

#17 Resized the country images
  Landing-pages/index.html
  Landing-pages/styles.css
Labels: hacktoberfest-accepted

#15 E-commerce website
  e-commerce webpage/shoppie-master/LICENSE
  e-commerce webpage/shoppie-master/README.md
  e-commerce webpage/shoppie-master/assets/css/style.css
  e-commerce webpage/shoppie-master/assets/fonts/ClashDisplay-Semibold.woff2
  e-commerce webpage/shoppie-master/assets/fonts/font.css
  e-commerce webpage/shoppie-master/assets/images/Thumbs.db
  e-commerce webpage/shoppie-master/assets/images/footer-shape-1.png
  e-commerce webpage/shoppie-master/assets/images/footer-shape-2.png
  e-commerce webpage/shoppie-master/assets/images/footer-shape-3.png
  e-commerce webpage/shoppie-master/assets/images/hero-banner.png
  e-commerce webpage/shoppie-master/assets/images/hero-shape-1.png
  e-commerce webpage/shoppie-master/assets/images/hero-shape-2.png
  e-commerce webpage/shoppie-master/assets/images/logo.svg
  e-commerce webpage/shoppie-master/assets/images/offer-bg.png
  e-commerce webpage/shoppie-master/assets/images/product-1.png
  e-commerce webpage/shoppie-master/assets/images/product-2.png
  e-commerce webpage/shoppie-master/assets/images/product-3.png
  e-commerce webpage/shoppie-master/assets/images/product-4.png
  e-commerce webpage/shoppie-master/assets/images/product-5.png
  e-commerce webpage/shoppie-master/assets/images/product-6.png
  e-commerce webpage/shoppie-master/assets/images/product-7.png
  e-commerce webpage/shoppie-master/assets/images/product-8.png
  e-commerce webpage/shoppie-master/assets/images/product-9.png
  e-commerce webpage/shoppie-master/assets/js/script.js
  e-commerce webpage/shoppie-master/favicon.svg
  e-commerce webpage/shoppie-master/index.html
  e-commerce webpage/shoppie-master/index.txt
  e-commerce webpage/shoppie-master/readme-images/desktop.png
  e-commerce webpage/shoppie-master/style-guide.md
Labels: Hactoberfest2023, hacktoberfest-accepted

#23 Footer_pages #1
  Footer_page/index.html
  Footer_page/style.css
Labels: hactoberfest, hacktoberfest-accepted

#22 E-commerce website built with reactJS
  E-commerce preview.png
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/img/product-1.png
  public/img/product-2.png
  public/img/product-3.png
  public/img/product-4.png
  public/img/product-5.png
  public/img/product-6.png
  public/img/product-7.png
  public/img/product-8.png
  public/index.html
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Button.js
  src/components/Cart/Cart.js
  src/components/Cart/CartColumns.js
  src/components/Cart/CartItem.js
  src/components/Cart/CartList.js
  src/components/Cart/CartTotals.js
  src/components/Cart/EmptyCart.js
  src/components/Cart/footer.js
  src/components/Cart/package.json
  src/components/Default.js
  src/components/Details.js
  src/components/Modal.js
  src/components/Navbar.js
  src/components/Product.js
  src/components/ProductList.js
  src/components/Title.js
  src/context.js
  src/data.js
  src/img/product-1.png
  src/img/product-2.png
  src/img/product-3.png
  src/img/product-4.png
  src/img/product-5.png
  src/img/product-6.png
  src/img/product-7.png
  src/img/product-8.png
  src/index.css
  src/index.js
  src/logo.svg
  src/serviceWorker.js
Labels: hactoberfest, hacktoberfest-accepted

#21 changed footer
  Landing-page/index.html
  Landing-page/style.css
Labels: hactoberfest, hacktoberfest-accepted

#19 Adding animation pages for browser.
  Animation-pages/animation.html
  Animation-pages/computerScience.html
  Animation-pages/googleWorkspace.html
  Animation-pages/index.html
  Animation-pages/main.css
  Animation-pages/script.js
  Animation-pages/socialMedia.html
Labels: hactoberfest, hacktoberfest-accepted

#18 Home page of website to book barbie movie ticket
  Mini Project/Barbie.html
  Mini Project/Barbie.png
  Mini Project/README.md
Labels: hactoberfest, hacktoberfest-accepted

#24 Super_hero_API_website
  Super_hero_API_app/index.html
  Super_hero_API_app/script.js
  Super_hero_API_app/style.css
Labels: hactoberfest, hacktoberfest-accepted

#25 Slider #3
  Slider/index.html
  Slider/style.css
Labels: hactoberfest, hacktoberfest-accepted

#26 responsive footer added #1
  Responsive-footer/index.html
  Responsive-footer/style.css
Labels: hactoberfest, hacktoberfest-accepted

#29 Added Calculator
  Calculator/index.html
  Calculator/index.js
  Calculator/style.css
Labels: hactoberfest, hacktoberfest-accepted

#28 Main
  payment_issue/css/style.css
  payment_issue/index.html
  payment_issue/script.js
Labels: hactoberfest, hacktoberfest-accepted

#27 Foodies Landing Page
  issue2Landing_page/images/bg/bg-1.jpg
  issue2Landing_page/images/bg/bg-2.jpg
  issue2Landing_page/images/bg/bg-3.jpg
  issue2Landing_page/images/img/img-1.png
  issue2Landing_page/images/img/img-2.png
  issue2Landing_page/images/img/img-3.jpg
  issue2Landing_page/images/img/img-4.jpg
  issue2Landing_page/images/img/img-5.jpg
  issue2Landing_page/images/logo.png
  issue2Landing_page/images/review/review-1.jpg
  issue2Landing_page/images/review/review-2.jpg
  issue2Landing_page/index.html
  issue2Landing_page/responsive-style.css
  issue2Landing_page/style.css
Labels: hactoberfest, hacktoberfest-accepted

#33 Temperature convertor using HTML, CSS & JS
  tempConvertor/index.html
  tempConvertor/script.js
  tempConvertor/style.css
Labels: hactoberfest, hacktoberfest-accepted

#40 -Mini-Website-
  mini-websites/R_mini-website/css/style.css
  mini-websites/R_mini-website/index.html
Labels: hacktoberfest-accepted

#38 Added Posture Detection using JS
  Posture Detection using JS/Readme.md
  Posture Detection using JS/images/Harbhajan.jpg
  Posture Detection using JS/images/one.txt
  Posture Detection using JS/index.html
  Posture Detection using JS/script.js
  Posture Detection using JS/sketch.js
  Sports Complex Web Page/Readme.md
  Sports Complex Web Page/dumbell.png
  Sports Complex Web Page/gym.jpg
  Sports Complex Web Page/gym.png
  Sports Complex Web Page/index.html
  Sports Complex Web Page/style.css
  Sports Complex Web Page/timer.js
  Sports Complex Web Page/utils.css
Labels: hacktoberfest-accepted

#36 build a Contact Us form
  Landing_page/index.html
  Landing_page/styles.css
Labels: hacktoberfest-accepted

#35 Changed an footer option and some css
  Footer_page/index.html
  Footer_page/style.css
Labels: hacktoberfest-accepted

#44 contribution for hactoberfest 2023
  package-lock.json
  package.json
  src/App.css
Labels: hacktoberfest-accepted

#46 A reactjs minor project that fetch random quotes from an api
  random-quote-generator/.gitignore
  random-quote-generator/README.md
  random-quote-generator/figmaDesign.png
  random-quote-generator/package-lock.json
  random-quote-generator/package.json
  random-quote-generator/public/index.html
  random-quote-generator/public/manifest.json
  random-quote-generator/public/quotation-mark.png
  random-quote-generator/public/robots.txt
  random-quote-generator/src/App.js
  random-quote-generator/src/App.test.js
  random-quote-generator/src/index.js
  random-quote-generator/src/reportWebVitals.js
  random-quote-generator/src/setupTests.js
  random-quote-generator/src/style.css
Labels: hacktoberfest-accepted

#45 adding an interface for a payment gateway
  payment gateway(updated)/home.html
  payment gateway(updated)/style.css
Labels: hacktoberfest-accepted

#48 added jsfunctionality in navbar
  issue2Landing_page/index.html
  issue2Landing_page/style.css
Labels: hacktoberfest-accepted

#53 random abuse generator
  random-Abuse/App.css
  random-Abuse/App.js
  random-Abuse/App.test.js
  random-Abuse/cuss.jsx
  random-Abuse/emoji.jsx
  random-Abuse/index.css
  random-Abuse/index.js
  random-Abuse/logo.svg
  random-Abuse/reportWebVitals.js
  random-Abuse/setupTests.js
Labels: hacktoberfest-accepted

#52 Changes the paymentissue.html file
  payment_issue/index.html
Labels: hacktoberfest-accepted

#51 Added a new file to generate qr code acoording to the user's input wh…
  qrcode_generator.py
Labels: hacktoberfest-accepted

#50 animated landing page using gsap animation library
  animatedLanding_page/index.html
  animatedLanding_page/styles.css
Labels: hacktoberfest-accepted

#56 Added Personal Portfolio Website - Hacktoberfest
  Portfolio Website/LICENSE.txt
  Portfolio Website/READ-ME.txt
  Portfolio Website/css/style.css
  Portfolio Website/img/about.jpg
  Portfolio Website/img/blog-1.jpg
  Portfolio Website/img/blog-2.jpg
  Portfolio Website/img/contact.jpg
  Portfolio Website/img/hero-bg.jpg
  Portfolio Website/img/hero.png
  Portfolio Website/img/portfolio-1.jpg
  Portfolio Website/img/portfolio-2.jpg
  Portfolio Website/img/portfolio-3.jpg
  Portfolio Website/img/portfolio-4.jpg
  Portfolio Website/img/portfolio-5.jpg
  Portfolio Website/img/portfolio-6.jpg
  Portfolio Website/img/team-1.jpg
  Portfolio Website/img/team-2.jpg
  Portfolio Website/img/team-3.jpg
  Portfolio Website/img/team-4.jpg
  Portfolio Website/img/testimonial-1.jpg
  Portfolio Website/img/testimonial-2.jpg
  Portfolio Website/img/testimonial-3.jpg
  Portfolio Website/index.html
  Portfolio Website/js/main.js
  Portfolio Website/lib/animate/animate.css
  Portfolio Website/lib/animate/animate.min.css
  Portfolio Website/lib/easing/easing.js
  Portfolio Website/lib/easing/easing.min.js
  Portfolio Website/lib/isotope/isotope.pkgd.js
  Portfolio Website/lib/isotope/isotope.pkgd.min.js
  Portfolio Website/lib/lightbox/css/lightbox.css
  Portfolio Website/lib/lightbox/css/lightbox.min.css
  Portfolio Website/lib/lightbox/images/close.png
  Portfolio Website/lib/lightbox/images/loading.gif
  Portfolio Website/lib/lightbox/images/next.png
  Portfolio Website/lib/lightbox/images/prev.png
  Portfolio Website/lib/lightbox/js/lightbox.js
  Portfolio Website/lib/lightbox/js/lightbox.min.js
  Portfolio Website/lib/lightbox/links.php
  Portfolio Website/lib/owlcarousel/LICENSE
  Portfolio Website/lib/owlcarousel/assets/ajax-loader.gif
  Portfolio Website/lib/owlcarousel/assets/owl.carousel.css
  Portfolio Website/lib/owlcarousel/assets/owl.carousel.min.css
  Portfolio Website/lib/owlcarousel/assets/owl.theme.default.css
  Portfolio Website/lib/owlcarousel/assets/owl.theme.default.min.css
  Portfolio Website/lib/owlcarousel/assets/owl.theme.green.css
  Portfolio Website/lib/owlcarousel/assets/owl.theme.green.min.css
  Portfolio Website/lib/owlcarousel/assets/owl.video.play.png
  Portfolio Website/lib/owlcarousel/owl.carousel.js
  Portfolio Website/lib/owlcarousel/owl.carousel.min.js
  Portfolio Website/lib/typed/typed.js
  Portfolio Website/lib/typed/typed.min.js
  Portfolio Website/lib/waypoints/links.php
  Portfolio Website/lib/waypoints/waypoints.min.js
  Portfolio Website/lib/wow/wow.js
  Portfolio Website/lib/wow/wow.min.js
  Portfolio Website/mail/contact.js
  Portfolio Website/mail/contact.php
  Portfolio Website/mail/jqBootstrapValidation.min.js
Labels: hactoberfest, hacktoberfest-accepted

#57 create 404 pages
  404-Pages/Neon 404/css/style.css
  404-Pages/Neon 404/index.html
Labels: hactoberfest, hacktoberfest-accepted

#64 Added a well curated Ewaste Management Website
  ewaste_website/LICENSE
  ewaste_website/README.md
  ewaste_website/Readme.md
  ewaste_website/package-lock.json
  ewaste_website/package.json
  ewaste_website/public/index.html
  ewaste_website/public/logo.png
  ewaste_website/public/preview.jpg
  ewaste_website/public/robots.txt
  ewaste_website/public/unnamed.jpg
  ewaste_website/src/App.js
  ewaste_website/src/components/Features/Features.js
  ewaste_website/src/components/Features/Features.module.css
  ewaste_website/src/components/Footer/Footer.js
  ewaste_website/src/components/Footer/Footer.module.css
  ewaste_website/src/components/Growth/Growth.js
  ewaste_website/src/components/Growth/Growth.module.css
  ewaste_website/src/components/Growth/GrowthBox.js
  ewaste_website/src/components/Hero/Hero.js
  ewaste_website/src/components/Hero/Hero.module.css
  ewaste_website/src/components/Navbar/Navbar.js
  ewaste_website/src/components/Navbar/Navbar.module.css
  ewaste_website/src/components/Navbar/logo2.png
  ewaste_website/src/components/NavbarResponsive/NavbarResponsive.js
  ewaste_website/src/components/Programs/Programs.js
  ewaste_website/src/components/Programs/Programs.module.css
  ewaste_website/src/components/Programs/ProgramsList.js
  ewaste_website/src/components/Programs/ProgramsRight.js
  ewaste_website/src/components/Programs/ProgramsRightResponsive.js
  ewaste_website/src/components/Questions/Questions.js
  ewaste_website/src/components/Questions/Questions.module.css
  ewaste_website/src/components/utils/Accordion.js
  ewaste_website/src/components/utils/Accordion.module.css
  ewaste_website/src/constants/features.js
  ewaste_website/src/constants/growth.js
  ewaste_website/src/constants/logo2.png
  ewaste_website/src/constants/programs_shopper.js
  ewaste_website/src/constants/programs_user.js
  ewaste_website/src/constants/questions.js
  ewaste_website/src/index.css
  ewaste_website/src/index.js
Labels: hactoberfest, hacktoberfest-accepted

#59 Dice Roller
  DiceRoller/img/1.jpeg
  DiceRoller/img/2.jpeg
  DiceRoller/img/3.jpeg
  DiceRoller/img/4.jpeg
  DiceRoller/img/5.jpeg
  DiceRoller/img/6.jpeg
  DiceRoller/index.css
  DiceRoller/index.html
  DiceRoller/index.js
Labels: hactoberfest, hacktoberfest-accepted

#69 Revert 2 patch 2
  payment_issue/index.html
Labels: hactoberfest, hacktoberfest-accepted

#66 my landing page
  My_LandingPage/1.png
  My_LandingPage/2.png
  My_LandingPage/3.png
  My_LandingPage/4.png
  My_LandingPage/5.png
  My_LandingPage/6.png
  My_LandingPage/index.html
  My_LandingPage/logo.png
  My_LandingPage/style.css
Labels: hactoberfest, hacktoberfest-accepted

#65 Added monster killer web game project
  Monster killer/assets/scripts/app.js
  Monster killer/assets/scripts/vendor.js
  Monster killer/assets/styles/app.css
  Monster killer/index.html
Labels: hactoberfest, hacktoberfest-accepted

#75 wikipedia clone project added
  wikipedia clone/README.md
  wikipedia clone/app.js
  wikipedia clone/index.html
  wikipedia clone/styles.css
  wikipedia clone/wiki-logo.png
  wikipedia clone/wiki-urls.js
Labels: hactoberfest, hacktoberfest-accepted

#74 Added a login page
  loginPage using HTML,CSS& JavaScript/index.html
  loginPage using HTML,CSS& JavaScript/scenaryimage1.jpg
  loginPage using HTML,CSS& JavaScript/style.css
Labels: hactoberfest, hacktoberfest-accepted

#71 Added Hunt-the-ace JavaScript game
  Hunt-the-ace/README.md
  Hunt-the-ace/images/AceSpades.png
  Hunt-the-ace/images/card-AceSpades.png
  Hunt-the-ace/images/card-JackClubs.png
  Hunt-the-ace/images/card-KingHearts.png
  Hunt-the-ace/images/card-QueenDiamonds.png
  Hunt-the-ace/images/card-back-Blue.png
  Hunt-the-ace/index.css
  Hunt-the-ace/index.html
  Hunt-the-ace/index.js
  ewaste_website/Readme.md
Labels: hactoberfest, hacktoberfest-accepted

#83 N-Queen-Prob and Rat-in-Maze
  N-Queen-Prob.cpp
  Rat-in-Maze.cpp
Labels: hactoberfest, hacktoberfest-accepted

#81 Added a new project called Image-Search-Engine
  Image-Search-Engine/app.js
  Image-Search-Engine/index.html
  Image-Search-Engine/style.css
  package.json
Labels: hacktoberfest-accepted

#79 added music website
  FoodWebsite/delivery.png
  FoodWebsite/discount.png
  FoodWebsite/food.css
  FoodWebsite/food.html
  FoodWebsite/fresh-1.png
  FoodWebsite/fresh.png
  FoodWebsite/grid_image1.png
  FoodWebsite/grid_image2.png
  FoodWebsite/grid_image3.png
  FoodWebsite/grid_image4.png
  FoodWebsite/grid_image5.png
  FoodWebsite/grid_image6.png
  FoodWebsite/grid_image7.png
  FoodWebsite/hero_image.png
  FoodWebsite/logo.png
  FoodWebsite/r.css
  Music Website/Unknown-removebg-preview-2.png
  Music Website/gift_card.png
  Music Website/hero_image.png
  Music Website/index.html
  Music Website/ipad-iphone.png
  Music Website/mac.png
  Music Website/project6.css
  Music Website/video.png
Labels: hactoberfest, hacktoberfest-accepted

#78 WeatherApp
  Weather/images/clear.png
  Weather/images/clouds.png
  Weather/images/drizzle.png
  Weather/images/humidity.png
  Weather/images/mist.png
  Weather/images/rain.png
  Weather/images/search.png
  Weather/images/snow.png
  Weather/images/wind.png
  Weather/index.html
  Weather/script.js
  Weather/style.css
Labels: hactoberfest, hacktoberfest-accepted

#77 added guess-my-number-game
  Guss-my-number/index.html
  Guss-my-number/script.js
  Guss-my-number/style.css
Labels: hactoberfest, hacktoberfest-accepted

#92 Added Text Reader App
  The Text Reader App/app.js
  The Text Reader App/index.html
  The Text Reader App/style.css
Labels: hactoberfest, hacktoberfest-accepted

#91 Add files via upload
  MultiStageGraph.java
  travelling_Salesman.java
Labels: hactoberfest, hacktoberfest-accepted

#90 add: created proper readme for the repo
  README.md
Labels: hactoberfest, hacktoberfest-accepted

#86 Added 2048 game in the repo
  2048 GAME/2048_cover_end.png
  2048 GAME/2048_cover_start.png
  2048 GAME/README.md
  2048 GAME/app.js
  2048 GAME/index.html
  2048 GAME/style.css
Labels: hactoberfest, hacktoberfest-accepted

#84 Added a project
  personal-landing-page/index.html
  personal-landing-page/style.css
Labels: hactoberfest, hacktoberfest-accepted

#95 Create Simple timer.js
  Simple timer.js
Labels: hacktoberfest-accepted

#96 Create deviceInternetStatus.html
  deviceInternetStatus.html
Labels: hactoberfest, hacktoberfest-accepted

#98 Added Disney+ Landing Page
  Disney+ clone/images/add.png
  Disney+ clone/images/disney.PNG
  Disney+ clone/images/geographic.PNG
  Disney+ clone/images/logo.png
  Disney+ clone/images/marvel.PNG
  Disney+ clone/images/nxt.png
  Disney+ clone/images/pixar.PNG
  Disney+ clone/images/play.png
  Disney+ clone/images/poster 1.png
  Disney+ clone/images/poster 10.png
  Disney+ clone/images/poster 11.png
  Disney+ clone/images/poster 12.png
  Disney+ clone/images/poster 2.png
  Disney+ clone/images/poster 3.png
  Disney+ clone/images/poster 4.png
  Disney+ clone/images/poster 5.png
  Disney+ clone/images/poster 6.png
  Disney+ clone/images/poster 7.png
  Disney+ clone/images/poster 8.png
  Disney+ clone/images/poster 9.png
  Disney+ clone/images/pre.png
  Disney+ clone/images/slider 1.PNG
  Disney+ clone/images/slider 2.PNG
  Disney+ clone/images/slider 3.PNG
  Disney+ clone/images/slider 4.PNG
  Disney+ clone/images/slider 5.PNG
  Disney+ clone/images/star-wars.PNG
  Disney+ clone/index.html
  Disney+ clone/index.js
  Disney+ clone/package.json
  Disney+ clone/sandbox.config.json
  Disney+ clone/style.css
  Disney+ clone/videos/disney.mp4
  Disney+ clone/videos/geographic.mp4
  Disney+ clone/videos/marvel.mp4
  Disney+ clone/videos/pixar.mp4
  Disney+ clone/videos/star-war.mp4
Labels: hactoberfest, hacktoberfest-accepted

#103 Added a Birthday Website
  Birthday_website/cake.html
  Birthday_website/cake.js
  Birthday_website/css/cake.css
  Birthday_website/css/header.css
  Birthday_website/css/letter.css
  Birthday_website/css/logo.css
  Birthday_website/css/nav.css
  Birthday_website/css/utility.css
  Birthday_website/home.html
  Birthday_website/img/bday2.jpeg
  Birthday_website/img/myuni.mp3
  Birthday_website/letter.html
Labels: hactoberfest, hacktoberfest-accepted

#106 Fooding App
  FoodPoint/index.html
  FoodPoint/script.js
  FoodPoint/style.css
  MarioGame/img/enemy.png
  MarioGame/img/mario.png
  MarioGame/img/track.png
  MarioGame/index.html
  MarioGame/script.js
  MarioGame/style.css
Labels: hactoberfest, hacktoberfest-accepted

#108 server_code_editor
  server.js
Labels: hactoberfest, hacktoberfest-accepted

#109 weather app
  weather-app/package-lock.json
  weather-app/package.json
  weather-app/public/css/styles.css
  weather-app/public/img/me.png
  weather-app/public/img/weather-icon.png
  weather-app/public/js/app.js
  weather-app/src/app.js
  weather-app/src/utils/forecast.js
  weather-app/src/utils/geocode.js
  weather-app/templates/partials/footer.hbs
  weather-app/templates/partials/header.hbs
  weather-app/templates/views/404.hbs
  weather-app/templates/views/about.hbs
  weather-app/templates/views/help.hbs
  weather-app/templates/views/index.hbs
Labels: hactoberfest, hacktoberfest-accepted

#110 Maked Note Web App
  MakeNotesApp/.vscode/settings.json
  MakeNotesApp/Demo.png
  MakeNotesApp/README.md
  MakeNotesApp/app.js
  MakeNotesApp/capture.jpeg
  MakeNotesApp/favicon.ico
  MakeNotesApp/index.html
  MakeNotesApp/index.php
Labels: hactoberfest, hacktoberfest-accepted
